### ISSUE TITLE
Feature Request: Inline Markdown Editing

### ISSUE THREAD

**Issue by stefan-niedermann** [falnatsheh/MarkdownView#13]
Hi,

it would be a really cool feature to be able to edit directly in the parsed markdown.
As a reference, see [ownCloud Notes](https://github.com/owncloud/notes), which is using [mdEdit](https://github.com/jbt/mdEdit) (Javascript Library)

Best Regards

**Comment by falnatsheh** [comment]
Yeah I used Dropbox Notes which do something similar, I think it's a good feature for specfic purposes. For the time being the library focuses on acting as a Markdown viewer but maybe in the future will add some kinda of edit mode. If you have ideas about the implementation or would like to share a pull requests will gladly look at them. Thanks

**Comment by stefan-niedermann** [comment]
Cool :) Did you have a look at the linked [mdEdit-Library](https://github.com/jbt/mdEdit)? It's originally written for a webapp, it's implemented in Javascript. As far as i understand, MarkdownView is using Webkit, so maybe the Code from mdEdit could be reused?

**Comment by falnatsheh** [comment]
I just noticed I didn't reply back, sorry for that. 

Do you mean like the right side of [this] page (https://jbt.github.io/markdown-editor)?

**Comment by stefan-niedermann** [comment]
Hmmm not really - the left side is able to edit, but not to render, the right side is able to render, but not editable.
Have a look at this video:
http://owncloud.niedermann.it/index.php/s/QBxov7OiwJf7vcv

I'd like to have one merged screen, where the text is editable *and* directly rendered in realtime.

hope the video can explain it better :)

**Comment by falnatsheh** [comment]
Oh I see what you mean, I use an app called Mou and it does something similar. That would be nice to have as an option although not sure if it will be part of MarkdownView itself or maybe a documentation in the wiki on how to integrate JS library that works with Android webview.

**Comment by stefan-niedermann** [comment]
Not longer relevant for me. Feel free to close.

**Comment by falnatsheh** [comment]
Thanks for the update. I think I will keep the lib focused on just previewing the markdown so will close this one.
