### ISSUE TITLE
update F-droid repo

### ISSUE THREAD

**Issue by jujes** [falnatsheh/MarkdownView#17]
please update to MarkdownView 1.1.0  F-droid repo...
thanks

**Comment by falnatsheh** [comment]
Hi @jujes, thanks for reporting this issue. I don't think I submitted the app to F-droid originally but I just submit the new version to the F-Droid Queue. Please keep an eye on the F-Droid thread [here](https://f-droid.org/forums/topic/markdownview/) for the update status.
