### ISSUE TITLE
How to show Bullet or numbered list

### ISSUE THREAD

**Issue by rohan2817** [falnatsheh/MarkdownView#18]
I am not able to see the bullet or number list, how to show using MarkdownView

Also if I try to set text from some string variable it is not rendered in markdown

**Comment by falnatsheh** [comment]
Can you please provide an example of the markdown you have tried. In case if you need more details about Markdown format, visit [this](https://daringfireball.net/projects/markdown/) link.

**Comment by falnatsheh** [comment]
I'm closing this for now but feel free to reopen it. To see an example of string variable markdown take a look at the example in the repo.
