### ISSUE TITLE
Bump versionCode

### ISSUE THREAD

**Issue by krt16s** [falnatsheh/MarkdownView#19]
You requested an update for the F-Droid version at https://f-droid.org/forums/topic/markdownview/, however your `build.gradle` file still says this is version "1.0" with versioncode "1". You have to bump at least the versioncode (an integer value), because that determines if it's an update or not. See: https://developer.android.com/studio/publish/versioning.html

**Comment by falnatsheh** [comment]
Thanks, I just updated the version code and number. 

https://github.com/falnatsheh/MarkdownView/commit/73fdf101dd15ad3eec15f559005d9ef7e4018a7d

**Comment by krt16s** [comment]
I was talking about the `app/build.gradle`, not the one of the library :p. I don't think versionname and vercode do even apply to libraries, but I am not sure...

**Comment by falnatsheh** [comment]
whoops 😄  ! alright fixing it right now.
