### ISSUE TITLE
Github Markdown

### ISSUE THREAD

**Issue by alorma** [falnatsheh/MarkdownView#22]
Hi!

Does this library supports `Github flavored Markdown`?

https://help.github.com/categories/writing-on-github/

**Comment by falnatsheh** [comment]
Hey @alorma! The lib uses MarkdownJ which only supports pure Markdown. I opened a ticket to support different processors including the ones that they support Github Flavored Markdown. #23

**Comment by falnatsheh** [comment]
Closing the issue, if you think task #23 does not include this feel free to reopen it and add more details.
