### ISSUE TITLE
How to make a table?

### ISSUE THREAD

**Issue by SohnyBohny** [falnatsheh/MarkdownView#25]
I've tried

``` java
String md = 
          "First Header   | Second Header\n" +
          "-------------  | -------------\n" +
          "*Content Cell* | Content Cell\n" +
          "Content Cell   | Content Cell";

mMarkdownView.loadMarkdown(md);
```

:boom: But it doesn't display a table

What do I wrong? - Please help! :shipit:

**Comment by SohnyBohny** [comment]
Thank you that works great! :-)

Is this Markdown completely supported?
https://daringfireball.net/projects/markdown/

**Comment by falnatsheh** [comment]
Yes! You could find more details about the processor that mdv uses [here](https://github.com/myabc/markdownj). 

> MarkdownJ is the pure Java port of Markdown (a text-to-html conversion tool written by John Gruber.)
