### ISSUE TITLE
is there a way to load a custom font?

### ISSUE THREAD

**Issue by gustavomc** [falnatsheh/MarkdownView#26]
how to load text with custom font?

**Comment by demetrio812** [comment]
I think I can help: put the css in the same directory of the fonts (inside the assets folder) and then add the following to your css (using the right font name):

```
@font-face {
 font-family: 'Lato-Light';
 src: url('Lato-Light.ttf')
}
```

Dem

**Comment by gustavomc** [comment]
but how can i set it to a string value programmatically? @demetrio812

**Comment by falnatsheh** [comment]
if you looked at the theme example in the sample app you will see this is done by having multiple CSS files. However, there's currently no support for changing the font programmatically without using CSS.
