### ISSUE TITLE
Can this library support code highlight and HTTPS connection?

### ISSUE THREAD

**Issue by Voyager2718** [falnatsheh/MarkdownView#27]
It seems that

``` Python
def HW():
    print('Hello, World!')
```

doesn't work.
And I can't use HTTPS connection such as the readme file of the project https://raw.githubusercontent.com/falnatsheh/MarkdownView/master/README.md

**Comment by falnatsheh** [comment]
Yes, I just tried the following URL and it rendered successfully using the sample app `https://raw.github.com/falnatsheh/MarkdownView/master/markdown-example.md`. 

<img width="259" alt="screenshot 2016-11-23 14 45 01" src="https://cloud.githubusercontent.com/assets/702474/20576305/758c3fd0-b18b-11e6-9173-caf60cb76a3c.png">
