### ISSUE TITLE
Errors in rendering multiple lists in a row

### ISSUE THREAD

**Issue by stephanepechard** [falnatsheh/MarkdownView#28]
Rendering lists works well when they have another text element separating them:
![screenshot_2016-11-22-15-12-58](https://cloud.githubusercontent.com/assets/703194/20526923/8350c340-b0c6-11e6-9889-af8ff51d40aa.png)

But when they follow each other (e.g. a numerical list followed by an item list), the second one is of the same type of the first, plus some random empty spaces are added.
![screenshot_2016-11-22-15-09-15](https://cloud.githubusercontent.com/assets/703194/20526902/667cc5f2-b0c6-11e6-85d9-5b08c73b2871.png)

Is this, as I think, a rendering error? Is there anything I can do to fix this from outside the library?

Thanks

**Comment by falnatsheh** [comment]
This is a bit late but I think this is related to how `MarkdownJ` (the processor that used by the lib) parse markdown to html unfortunately. Other processors might support this and there's a ticket to support them #23.
