### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by roman-ku** [falnatsheh/MarkdownView#32]
I was going to simplify one of app pages with this app but it's very slow.

I am using `ByteArrayOutputStream` to convert my raw markdown file into a string and then use this library (https://github.com/Uncodin/bypass) to set it to a textview and the difference is night and day.

**Comment by falnatsheh** [comment]
Hey @roman-ku, it's a tradeoff. In Bypass, you skip HTML and you will be able to convert and display markdown faster, in MarkdownView it's based on WebView displaying markdown converted to HTML, which gives you the ability to style it easily with CSS along with other advantages of using a WebView.
