### ISSUE TITLE
Cannot Embed images

### ISSUE THREAD

**Issue by pujitm** [falnatsheh/MarkdownView#37]
This is most likely an error on my part:  

I have several local image files linked in an MD file like so:
`![AdvDisNeutral1](AdvDisNeutral1.png)`

However, they do not show up. What syntax should I use?
This MD file is in the assets folder along with the images embedded in them.

Just a note: text renders perfectly.

**Comment by falnatsheh** [comment]
Hey! if you have them on your assets folder then you could do the following: `![Android Logo](file:///android_asset/google_android.png)`
