### ISSUE TITLE
Why does it need access to the internet?

### ISSUE THREAD

**Issue by aguaviva** [falnatsheh/MarkdownView#39]
Just wondering before installing.

**Comment by falnatsheh** [comment]
Hi, you could load Markdown files that are hosted remotely, see the code [here](https://github.com/falnatsheh/MarkdownView/blob/58e6298f38a8c5efa141285e47e589e50d4e5e73/MarkdownView/markdownview/src/main/java/us/feras/mdv/MarkdownView.java#L108). However, you don’t need internet permissions if you’re loading local files.
