### ISSUE TITLE
Crashes if loading cssFile and html has %-characters

### ISSUE THREAD

**Issue by swanson** [falnatsheh/MarkdownView#7]
https://github.com/falnatsheh/MarkdownView/blob/master/MarkdownView/src/us/feras/mdv/MarkdownView.java#L132

This will throw an exception if html has any String.format tokens in it - for example `%20` in a URL. Should either construct the `<link>` tag separately or just concatenate and don't use String.format

**Comment by falnatsheh** [comment]
Thank you, it's fixed now.
