### ISSUE TITLE
Add installation process to main project page

### ISSUE THREAD

**Issue by proverbface** [falnatsheh/MarkdownView#8]
I tried to use your library through compiling the project and including the jar file into my project, but either ways I was not able to use it.

a)  I tried adding the next lines to my settings.gradle
def markdownView = file('../MarkdownView/MarkdownView' )
settings.createProjectDescriptor( rootProjectDescriptor, 'markdown-view', markdownView )
include ':markdown-view'

and to my build.gradle
   compile project( ':markdown-view')

The result is that the Android Studio (v.0.8.6) says: Error:Configuration with name 'default' not found.

b) I tried adding the jar file markdownview-1.2.jar into the libs folder but for some reason when I want to use the MarkdownView class that is not in the classpath.

Any suggestion? I think the library looks quite well, but could be really handy if you could add the installation process.

I think the best way to include your project is through the first solution because I everyone can pull the repository and rebuild the project, getting the latest changes.

**Comment by falnatsheh** [comment]
The project converted to Gradle. Thanks.
